# Generated by Django 3.2.23 on 2024-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UPCLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(choices=[(1, 'Peruano'), (2, 'Extranjero')])),
                ('name', models.CharField(max_length=50)),
                ('last_name_one', models.CharField(max_length=50)),
                ('last_name_two', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('1', 'DNI'), ('2', 'Pasaporte')], max_length=2)),
                ('document_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('cellphone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('city', models.IntegerField(blank=True, null=True)),
                ('guid_client', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign_has_reference', models.CharField(max_length=30)),
                ('digital_channel', models.CharField(max_length=2)),
                ('format', models.CharField(blank=True, max_length=3, null=True)),
                ('inscription', models.IntegerField(default=0)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('pdp_version', models.CharField(blank=True, max_length=60, null=True)),
                ('pdp_authorization_date', models.DateTimeField(blank=True, null=True)),
                ('pdp_authorization', models.BooleanField(default=False)),
                ('history_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_phase', models.CharField(default=1, max_length=1)),
                ('period_interest', models.CharField(max_length=50)),
                ('state_sale', models.CharField(blank=True, max_length=3, null=True)),
                ('sub_state_sale', models.CharField(blank=True, max_length=3, null=True)),
                ('product_one', models.CharField(max_length=50)),
                ('sede_product_interest_1', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_channel', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_year', models.CharField(max_length=4)),
                ('create_month', models.CharField(max_length=2)),
                ('create_day', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'UPCLead',
                'verbose_name_plural': 'UPCLeads',
                'db_table': 'upc_leads',
            },
        ),
    ]
