# Generated by Django 3.2.23 on 2024-02-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upclead',
            name='create_day',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='upclead',
            name='create_month',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='upclead',
            name='create_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
